ALTER TYPE "HouseholdAuditAction" ADD VALUE 'recipe_created';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'recipe_updated';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'recipe_deleted';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'food_inventory_created';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'food_inventory_updated';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'food_inventory_deleted';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'meal_plan_created';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'meal_plan_updated';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'meal_plan_deleted';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'shopping_entry_created';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'shopping_entry_updated';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'shopping_entry_deleted';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_location_created';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_location_updated';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_location_deleted';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_container_created';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_container_updated';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_container_deleted';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_item_created';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_item_updated';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_item_deleted';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_label_created';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_label_updated';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_label_deleted';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_qr_generated';
ALTER TYPE "HouseholdAuditAction" ADD VALUE 'storage_qr_revoked';
CREATE TYPE "HouseholdFoodLocation" AS ENUM ('pantry', 'fridge', 'freezer');

CREATE TABLE "HouseholdRecipe" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "instructions" TEXT, "servings" DECIMAL(10,2), "prepMinutes" INTEGER, "cookMinutes" INTEGER, "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HouseholdRecipe_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HouseholdRecipeIngredient" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "recipeId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "name" TEXT NOT NULL, "quantity" DECIMAL(14,3), "unit" TEXT, "notes" TEXT, "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HouseholdRecipeIngredient_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HouseholdFoodInventory" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "name" TEXT NOT NULL, "location" "HouseholdFoodLocation" NOT NULL, "quantity" DECIMAL(14,3) NOT NULL DEFAULT 0, "unit" TEXT, "expiresAt" TIMESTAMP(3), "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HouseholdFoodInventory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HouseholdMealPlan" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "recipeId" TEXT, "title" TEXT NOT NULL, "plannedFor" TIMESTAMP(3) NOT NULL, "mealType" TEXT, "servings" DECIMAL(10,2), "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HouseholdMealPlan_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HouseholdShoppingListEntry" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "name" TEXT NOT NULL, "quantity" DECIMAL(14,3), "unit" TEXT, "checked" BOOLEAN NOT NULL DEFAULT false, "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HouseholdShoppingListEntry_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HouseholdStorageLocation" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HouseholdStorageLocation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HouseholdStorageContainer" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "locationId" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "positionText" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HouseholdStorageContainer_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HouseholdStorageItem" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "locationId" TEXT NOT NULL, "containerId" TEXT, "name" TEXT NOT NULL, "description" TEXT, "quantity" DECIMAL(14,3) NOT NULL DEFAULT 1, "unit" TEXT, "positionText" TEXT, "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HouseholdStorageItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HouseholdStorageLabel" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "itemId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "value" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HouseholdStorageLabel_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HouseholdStorageQrReference" ("id" TEXT NOT NULL, "householdId" TEXT NOT NULL, "itemId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "tokenHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "HouseholdStorageQrReference_pkey" PRIMARY KEY ("id"));

CREATE INDEX "HouseholdRecipe_householdId_name_idx" ON "HouseholdRecipe"("householdId", "name");
CREATE INDEX "HouseholdRecipe_createdById_idx" ON "HouseholdRecipe"("createdById");
CREATE INDEX "HouseholdRecipeIngredient_householdId_recipeId_sortOrder_idx" ON "HouseholdRecipeIngredient"("householdId", "recipeId", "sortOrder");
CREATE INDEX "HouseholdRecipeIngredient_createdById_idx" ON "HouseholdRecipeIngredient"("createdById");
CREATE INDEX "HouseholdFoodInventory_householdId_location_expiresAt_idx" ON "HouseholdFoodInventory"("householdId", "location", "expiresAt");
CREATE INDEX "HouseholdFoodInventory_createdById_idx" ON "HouseholdFoodInventory"("createdById");
CREATE INDEX "HouseholdMealPlan_householdId_plannedFor_idx" ON "HouseholdMealPlan"("householdId", "plannedFor");
CREATE INDEX "HouseholdMealPlan_recipeId_idx" ON "HouseholdMealPlan"("recipeId");
CREATE INDEX "HouseholdMealPlan_createdById_idx" ON "HouseholdMealPlan"("createdById");
CREATE INDEX "HouseholdShoppingListEntry_householdId_checked_createdAt_idx" ON "HouseholdShoppingListEntry"("householdId", "checked", "createdAt");
CREATE INDEX "HouseholdShoppingListEntry_createdById_idx" ON "HouseholdShoppingListEntry"("createdById");
CREATE INDEX "HouseholdStorageLocation_householdId_name_idx" ON "HouseholdStorageLocation"("householdId", "name");
CREATE INDEX "HouseholdStorageLocation_createdById_idx" ON "HouseholdStorageLocation"("createdById");
CREATE INDEX "HouseholdStorageContainer_householdId_locationId_name_idx" ON "HouseholdStorageContainer"("householdId", "locationId", "name");
CREATE INDEX "HouseholdStorageContainer_createdById_idx" ON "HouseholdStorageContainer"("createdById");
CREATE INDEX "HouseholdStorageItem_householdId_name_idx" ON "HouseholdStorageItem"("householdId", "name");
CREATE INDEX "HouseholdStorageItem_locationId_idx" ON "HouseholdStorageItem"("locationId");
CREATE INDEX "HouseholdStorageItem_containerId_idx" ON "HouseholdStorageItem"("containerId");
CREATE INDEX "HouseholdStorageItem_createdById_idx" ON "HouseholdStorageItem"("createdById");
CREATE UNIQUE INDEX "HouseholdStorageLabel_itemId_value_key" ON "HouseholdStorageLabel"("itemId", "value");
CREATE INDEX "HouseholdStorageLabel_householdId_value_idx" ON "HouseholdStorageLabel"("householdId", "value");
CREATE INDEX "HouseholdStorageLabel_createdById_idx" ON "HouseholdStorageLabel"("createdById");
CREATE UNIQUE INDEX "HouseholdStorageQrReference_tokenHash_key" ON "HouseholdStorageQrReference"("tokenHash");
CREATE INDEX "HouseholdStorageQrReference_householdId_itemId_idx" ON "HouseholdStorageQrReference"("householdId", "itemId");
CREATE INDEX "HouseholdStorageQrReference_createdById_idx" ON "HouseholdStorageQrReference"("createdById");

ALTER TABLE "HouseholdRecipe" ADD CONSTRAINT "HouseholdRecipe_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdRecipe" ADD CONSTRAINT "HouseholdRecipe_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HouseholdRecipeIngredient" ADD CONSTRAINT "HouseholdRecipeIngredient_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdRecipeIngredient" ADD CONSTRAINT "HouseholdRecipeIngredient_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "HouseholdRecipe"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdRecipeIngredient" ADD CONSTRAINT "HouseholdRecipeIngredient_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HouseholdFoodInventory" ADD CONSTRAINT "HouseholdFoodInventory_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdFoodInventory" ADD CONSTRAINT "HouseholdFoodInventory_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HouseholdMealPlan" ADD CONSTRAINT "HouseholdMealPlan_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdMealPlan" ADD CONSTRAINT "HouseholdMealPlan_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "HouseholdRecipe"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "HouseholdMealPlan" ADD CONSTRAINT "HouseholdMealPlan_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HouseholdShoppingListEntry" ADD CONSTRAINT "HouseholdShoppingListEntry_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdShoppingListEntry" ADD CONSTRAINT "HouseholdShoppingListEntry_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageLocation" ADD CONSTRAINT "HouseholdStorageLocation_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageLocation" ADD CONSTRAINT "HouseholdStorageLocation_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageContainer" ADD CONSTRAINT "HouseholdStorageContainer_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageContainer" ADD CONSTRAINT "HouseholdStorageContainer_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "HouseholdStorageLocation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageContainer" ADD CONSTRAINT "HouseholdStorageContainer_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageItem" ADD CONSTRAINT "HouseholdStorageItem_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageItem" ADD CONSTRAINT "HouseholdStorageItem_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "HouseholdStorageLocation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageItem" ADD CONSTRAINT "HouseholdStorageItem_containerId_fkey" FOREIGN KEY ("containerId") REFERENCES "HouseholdStorageContainer"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageItem" ADD CONSTRAINT "HouseholdStorageItem_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageLabel" ADD CONSTRAINT "HouseholdStorageLabel_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageLabel" ADD CONSTRAINT "HouseholdStorageLabel_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "HouseholdStorageItem"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageLabel" ADD CONSTRAINT "HouseholdStorageLabel_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageQrReference" ADD CONSTRAINT "HouseholdStorageQrReference_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageQrReference" ADD CONSTRAINT "HouseholdStorageQrReference_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "HouseholdStorageItem"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HouseholdStorageQrReference" ADD CONSTRAINT "HouseholdStorageQrReference_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;