// Flat ESLint config for `yarn lint` (`eslint .`). Next.js 16 removed `next lint`,
// so this file is the lint entry point; eslint-config-next 16 ships flat configs.
import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

export default defineConfig([
  // Playwright's trace viewer bundles are generated third-party JavaScript, not
  // application source. Linting them creates thousands of irrelevant findings.
  globalIgnores([
    '.next/**',
    '.build/**',
    'node_modules/**',
    'out/**',
    'build/**',
    'playwright-report/**',
    'test-results/**',
    // Generated by the platform; it is managed outside application source.
    'instrumentation-client.js',
    'next-env.d.ts',
  ]),
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      'react/no-unescaped-entities': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/use-memo': 'off',
      'react-hooks/purity': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-unused-vars': 'error',
    },
  },
  {
    // This SWR fetcher is outside a Client Component, so it cannot use the
    // router hook; a full-page redirect is intentional for auth recovery.
    files: ['hooks/use-household.ts'],
    rules: {
      '@next/next/no-location-assign-relative-destination': 'off',
    },
  },
  {
    files: ['app/(app)/liabilities/liabilities-client.tsx'],
    rules: {
      'react-hooks/exhaustive-deps': 'off',
    },
  },
  {
    files: ['app/(app)/pathology/pathology-client.tsx'],
    rules: {
      '@next/next/no-img-element': 'off',
    },
  },
]);
